version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - COUCHBASE_CONNECTION_STRING=couchbase://couchbase
      - COUCHBASE_USERNAME=Administrator
      - COUCHBASE_PASSWORD=password
      - COUCHBASE_BUCKET_NAME=todo-app
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXPIRATION=86400000
      - SERVER_PORT=8080
    depends_on:
      - couchbase

  couchbase:
    image: couchbase:community
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data: 