package com.erailea.todoappclone.service.impl;

import com.erailea.todoappclone.dto.request.CreateNoteRequest;
import com.erailea.todoappclone.dto.request.UpdateNoteRequest;
import com.erailea.todoappclone.exception.ResourceNotFoundException;
import com.erailea.todoappclone.model.Note;
import com.erailea.todoappclone.repository.NoteRepository;
import com.erailea.todoappclone.repository.TodoListRepository;
import com.erailea.todoappclone.service.NoteService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class NoteServiceImpl implements NoteService {
    private final NoteRepository noteRepository;
    private final TodoListRepository todoListRepository;

    @Override
    public Note createNote(CreateNoteRequest request, String listId, String userId) {
        // Verify list exists and belongs to user
        if (todoListRepository.countByIdAndUserIdAndNotDeleted(listId, userId) == 0) {
            throw new ResourceNotFoundException("TodoList", "id", listId);
        }

        Note note = new Note(
                null, // ID will be generated by Couchbase
                request.getContent(),
                false,
                LocalDateTime.now(),
                request.getDueDate(),
                listId,
                null // deletedAt is null for new notes
        );
        return noteRepository.save(note);
    }

    @Override
    public List<Note> getNotesByListId(String listId, String userId) {
        // Verify list exists and belongs to user
        if (todoListRepository.countByIdAndUserIdAndNotDeleted(listId, userId) == 0) {
            throw new ResourceNotFoundException("TodoList", "id", listId);
        }

        return noteRepository.findAllByListIdAndDeletedAtIsNull(listId);
    }

    @Override
    public Note getNoteById(String id, String userId) {
        Note note = noteRepository.findByIdAndDeletedAtIsNull(id)
                .orElseThrow(() -> new ResourceNotFoundException("Note", "id", id));

        // Verify list exists and belongs to user
        if (todoListRepository.countByIdAndUserIdAndNotDeleted(note.getListId(), userId) == 0) {
            throw new ResourceNotFoundException("TodoList", "id", note.getListId());
        }

        return note;
    }

    @Override
    public Note updateNote(String id, UpdateNoteRequest request, String userId) {
        Note note = noteRepository.findByIdAndDeletedAtIsNull(id)
                .orElseThrow(() -> new ResourceNotFoundException("Note", "id", id));

        // Verify current list exists and belongs to user
        if (todoListRepository.countByIdAndUserIdAndNotDeleted(note.getListId(), userId) == 0) {
            throw new ResourceNotFoundException("TodoList", "id", note.getListId());
        }

        if (request.getContent() != null) {
            note.setContent(request.getContent());
        }
        if (request.getDone() != null) {
            note.setDone(request.getDone());
        }
        if (request.getDueDate() != null) {
            note.setDueDate(request.getDueDate());
        }
        if (request.getTargetListId() != null) {
            // Verify new list exists and belongs to user
            if (todoListRepository.countByIdAndUserIdAndNotDeleted(request.getTargetListId(), userId) == 0) {
                throw new ResourceNotFoundException("TodoList", "id", request.getTargetListId());
            }

            note.setListId(request.getTargetListId());
        }

        return noteRepository.save(note);
    }

    @Override
    public void deleteNote(String id, String userId) {
        Note note = noteRepository.findByIdAndDeletedAtIsNull(id)
                .orElseThrow(() -> new ResourceNotFoundException("Note", "id", id));

        // Verify list exists and belongs to user
        if (todoListRepository.countByIdAndUserIdAndNotDeleted(note.getListId(), userId) == 0) {
            throw new ResourceNotFoundException("TodoList", "id", note.getListId());
        }

        note.setDeletedAt(LocalDateTime.now());
        noteRepository.save(note);
    }
} 