name: Test Coverage

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  workflow_dispatch: 

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Coverage
        run: mvn clean verify
        working-directory: ./backend

      - name: Upload coverage report
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./backend/target/site/jacoco

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: jekyll

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4