name: Frontend Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/main-deploy-fe.yml'
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image for Heroku
        run: |
          # Build with API URL from GitHub secrets
          docker build --platform linux/amd64 \
            --build-arg VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL }}" \
            -t registry.heroku.com/to-do-app-clone-fe/web ./frontend

      - name: Push image to Heroku
        run: |
          docker push registry.heroku.com/to-do-app-clone-fe/web

      - name: Set Heroku environment variables
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/to-do-app-clone-fe/config-vars \
            -d '{"VITE_API_BASE_URL":"${{ secrets.VITE_API_BASE_URL }}"}' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3" \
            -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}"

      - name: Release image on Heroku
        run: |
          IMAGE_ID=$(docker inspect registry.heroku.com/to-do-app-clone-fe/web --format={{.Id}})
          curl -n -X PATCH https://api.heroku.com/apps/to-do-app-clone-fe/formation \
            -d "{\"updates\":[{\"type\":\"web\",\"docker_image\":\"${IMAGE_ID}\"}]}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" 